### ISSUE TITLE
Why it contain another python?

### ISSUE THREAD

**Issue by JohnWong** [square/PonyDebugger#115]
When I install PonyDebugger, another python environment is installed inside PonyDebugger. It really confused me. Many python libs are installed into the wrong position. Why not use the python already installed. My computer is Mac OSX 10.9.3.

**Comment by davidapgar** [comment]
PonyDebugger uses virtualenv (https://virtualenv.pypa.io/en/latest/) to have an isolated environment. The intent of this is to ensure that it does not end up having conflicting dependencies that are installed on the system.

(Doing some house-keeping, so closing out older issues)
