### ISSUE TITLE
Bootstrap script silently fails on OS X 10.9.4

### ISSUE THREAD

**Issue by pnc** [square/PonyDebugger#125]
_Just noticed this is a duplicate of #116._

Running the bootstrap script per the instructions fails silently: no output, no ponyd.

    > curl -sk https://cloud.github.com/downloads/square/PonyDebugger/bootstrap-ponyd.py | python - --pnonyd-symlink=/usr/local/bin/ponyd ~/Library/PonyDebugger
    > 

It appears that cURL is failing to even start a valid TLS session with GitHub, so it's not even getting to certificate validation where `-k` would be useful:

    > curl -vk https://cloud.github.com/downloads/square/PonyDebugger/bootstrap-ponyd.py
    > curl: (35) Unknown SSL protocol error in connection to cloud.github.com:-9824

Simply removing the `-k` option worked fine for me:

    > curl -s https://cloud.github.com/downloads/square/PonyDebugger/bootstrap-ponyd.py | python - --ponyd-symlink=/usr/local/bin/ponyd ~/Library/PonyDebugger

It might be worth removing the `-k` option from the README entirely, since it's spooky to execute unauthenticated Python code, and since it fails silently (at least in this case.)

This may or may not  be related to the [GitHub certificate weirdness on OS X.](http://superuser.com/questions/605900/why-wont-os-x-trust-githubs-ssl-certificate)

curl version:

    curl 7.30.0 (x86_64-apple-darwin13.0) libcurl/7.30.0 SecureTransport zlib/1.2.5
    Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smtp smtps telnet tftp 
    Features: AsynchDNS GSS-Negotiate IPv6 Largefile NTLM NTLM_WB SSL libz

**Comment by Ashton-W** [comment]
:+1: removing `-k` worked for me too. Thanks @pnc

**Comment by JasonWorking** [comment]
Agree, `-k` should be removed as it fails silently.

**Comment by pnc** [comment]
I have *no idea* why I didn't make this a pull request to begin with, but it's done now, as #152!
