### ISSUE TITLE
Is it possible to use PonyDebugger for OS X development ?

### ISSUE THREAD

**Issue by TXF** [square/PonyDebugger#134]
I encountered a problem when tried to install PonnyDebugger by means of cocoa pods.
I got an error:
[!] The platform of the target `SampleApp` (OS X 10.9) is not compatible with `PonyDebugger (0.4.0)` which has a minimum requirement of iOS 5.0.

Does it mean that Ponny works only with iOS ?

**Comment by NickEntin** [comment]
PonyDebugger does not currently support OS X development.  We would love a PR if you are interested in adding support.  Closing this out for now since this isn't something that we're actively working on and we're doing some housecleaning.
