### ISSUE TITLE
Using in Swift

### ISSUE THREAD

**Issue by tonglil** [square/PonyDebugger#137]
I have linked the libraries and the set up outlined in "manual installation". However when I try to implement the actual debugger instance I don't know how to import PonyDebugger into Swift so that it recognizes "PDDebugger".

```
        let pony = PDDebugger.defaultInstance()
        pony.connectToURL(NSURL.URLWithString("ws://localhost:9000/device"))
        pony.enableNetworkTrafficDebugging()
        pony.enableCoreDataDebugging()
```

**Comment by ChuckPinkert** [comment]
I've tried this by adding it my swift project via cocoapods and then adding the following to my bridgin-header file:
```
 #import <PonyDebugger/PonyDebugger.h>
or
 #import <PonyDebugger/PDDebugger.h>
or 
 #import "PonyDebugger/PonyDebugger.h"
or
 #import "PonyDebugger/PDDebugger.h"
```

and none of these allow me to resolve the identifier PDDebugger. Every other obj-c library I've imported via the bridging-header has seemed to work fine, is there something else I'm missing?
