### ISSUE TITLE
Debugger Tools

### ISSUE THREAD

**Issue by jcampbell05** [square/PonyDebugger#139]
Is there plans to have the debugger tools as part of a separate IDE ? Would be awesome if it could be integrated into xcode.

**Comment by auchenberg** [comment]
Just pitching in here. I'm planning making PonyDebugger working with [chrome-devtools-app](https://github.com/auchenberg/chrome-devtools-app), which is a stand-alone version of Chrome DevTools, that could evolve into an IDE.
