### ISSUE TITLE
warnings in new Xcode in PDDOMDomainController and PDInspectorDomainController

### ISSUE THREAD

**Issue by mackuba** [square/PonyDebugger#149]
Xcode 6.3 says:

> PDDOMDomainController.h:19:44: Auto property synthesis will not synthesize property 'domain'; it will be implemented by its superclass, use `@dynamic` to acknowledge intention

> PDInspectorDomainController.h:17:50: Auto property synthesis will not synthesize property 'domain'; it will be implemented by its superclass, use `@dynamic` to acknowledge intention

**Comment by davidapgar** [comment]
I just tested and build with Xcode 6.4, and don't seen warning/errors for these cases (build cleans with warning).

Closing this, if it does still reproduce for you off of master, please reopen.

**Comment by mackuba** [comment]
Yup, looks clean now, thanks.
