### ISSUE TITLE
Expanding triangles don't work in Google Chrome

### ISSUE THREAD

**Issue by Epskampie** [square/PonyDebugger#157]
The expanding triangles you see when inspecting a json response in the network inspector won't work in the current Google Chrome version (43).

The console shows the following error:

```
Uncaught TypeError: window.getComputedStyle(...).getPropertyCSSValue is not a function
```

If found a [similar problem](https://github.com/node-inspector/node-inspector/issues/478) with a [fix for the problem](https://github.com/node-inspector/node-inspector/pull/479/files).

**Comment by sebfie** [comment]
Same issue for me.

**Comment by efirestone** [comment]
Same as https://github.com/square/PonyDebugger/issues/67?

**Comment by A1iAshoor** [comment]
+1

**Comment by Epskampie** [comment]
Just use safari, it works there.

**Comment by A1iAshoor** [comment]
@Epskampie safari worked fine, I fixed the issue in chrome by modifying the JS files

**Comment by Epskampie** [comment]
Cool. Can you make a Pull Request of this, so that everyone can benefit?

**Comment by danielribeiro** [comment]
Seems to be related to the fact that the old dev tools project used by pony debugger leverages deprecated DOM methods.

**In Chrome 45.0.2454.101 (64-bit):**

<img width="1412" alt="screen shot 2015-10-02 at 4 52 46 pm" src="https://cloud.githubusercontent.com/assets/148319/10260168/b0627380-6926-11e5-9ec2-25f1b08f72d5.png">

**On Safari Version 8.0.8 (10600.8.9)**

<img width="1403" alt="screen shot 2015-10-02 at 4 55 47 pm" src="https://cloud.githubusercontent.com/assets/148319/10260171/ce4e6426-6926-11e5-98b0-6d498d2c582d.png">

Deprecation of *getPropertyCSSValue* was apparently announced almost a year ago:

https://groups.google.com/a/chromium.org/forum/#!msg/blink-dev/3VmxWFzcyJc/GFOnJxnWBN0J
