### ISSUE TITLE
Can't install python script

### ISSUE THREAD

**Issue by ThomasCassany** [square/PonyDebugger#167]
Hi,
I've this error when I try to install the script

 curl -s https://cloud.github.com/downloads/square/PonyDebugger/bootstrap-ponyd.py | python - --ponyd-symlink=/usr/local/bin/ponyd ~/Library/PonyDebugger

New python executable in /Users/thomas.cassany/Library/PonyDebugger/bin/python
Installing setuptools...............done.
Installing pip..............done.
Obtaining ponydebugger from git+https://github.com/square/PonyDebugger.git#egg=ponydebugger
  Updating ./Library/PonyDebugger/src/ponydebugger clone
fatal: unable to connect to github.com:
github.com[0: 192.30.252.131]: errno=Connection refused

Clone of 'git://github.com/square/SocketRocket.git' into submodule path 'pages' failed
Failed to recurse into submodule path 'ObjC/SocketRocket'
  Complete output from command git submodule update --init --recursive -q:
  
  ----------------------------------------
Command "git submodule update --init --recursive -q" failed with error code 1 in /Users/thomas.cassany/Library/PonyDebugger/src/ponydebugger
Traceback (most recent call last):
  File "<stdin>", line 2462, in <module>
  File "<stdin>", line 946, in main
  File "<stdin>", line 1794, in after_install
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Users/thomas.cassany/Library/PonyDebugger/bin/pip', 'install', '-U', '-e', 'git+https://github.com/square/PonyDebugger.git#egg=ponydebugger']' returned non-zero exit status 1

Any idea?

Thanks

**Comment by efirestone** [comment]
`fatal: unable to connect to github.com:`

This looks like an issue with reaching github.com. Can you reach it in the browser? Would you be behind a firewall for any reason? This doesn't look to be a PonyDebugger issue.
