### ISSUE TITLE
In Chrome not work

### ISSUE THREAD

**Issue by 1taypan** [square/PonyDebugger#169]
Chrome Version 45.0.2454.85 (64-bit)

http://localhost:9000/devtools/devtools.html?host=localhost:9000&page=2
Recources were core data

TypeError: Cannot read property 'length' of undefined
http://localhost:9000/devtools/CSSCompletions.js:42

TypeError: Cannot read property 'length' of undefined
http://localhost:9000/devtools/ResourceTreeModel.js:343

TypeError: window.getComputedStyle(...).getPropertyCSSValue is not a function
http://localhost:9000/devtools/treeoutline.js:1120

in Safari work fine and more fast

**Comment by dfed** [comment]
I think this is #157
