### ISSUE TITLE
Error: Redefinition of 'Category' as different kind of symbol 

### ISSUE THREAD

**Issue by engmsaleh** [square/PonyDebugger#176]
When I have installed PonyDebugger using Cocoapods, I have got the following error 
```
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.1.sdk/usr/include/objc/runtime.h:50:31: Redefinition of 'Category' as different kind of symbol
```

**Comment by kenwigginton** [comment]
@engmsaleh  Can you give a little more information? We use PonyDebugger with CocoaPods and do not have this issue.

Sounds like you have some code where you redefine the word "Category" as an interface or implementation or something. I refer you to http://stackoverflow.com/questions/6814694/error-category-declared-as-different-kind-of-symbol-in-xcode-4
