### ISSUE TITLE
Can't install. Git timeout

### ISSUE THREAD

**Issue by davidhodge** [square/PonyDebugger#18]
Not sure if this is on my end or what, but I keep getting timeouts when I use the bootstrap script. Here's the output I keep seeing. Any thoughts on this?

Thanks!

Serenity:~ david$ curl -sk https://cloud.github.com/downloads/square/PonyDebugger/bootstrap-ponyd.py |   python - --ponyd-symlink=/usr/local/bin/ponyd ~/Library/PonyDebugger
New python executable in /Users/david/Library/PonyDebugger/bin/python
Installing setuptools..................done.
Installing pip.............done.
Obtaining ponydebugger from git+https://github.com/square/PonyDebugger.git#egg=ponydebugger
  Cloning https://github.com/square/PonyDebugger.git to ./Library/PonyDebugger/src/ponydebugger
error: Failed connect to github.com:8888; Operation timed out while accessing https://github.com/square/PonyDebugger.git/info/refs
fatal: HTTP request failed
  Complete output from command /usr/bin/git clone -q https://github.com/square/PonyDebugger.git /Users/david/Library/PonyDebugger/src/ponydebugger:
  
----------------------------------------
Command /usr/bin/git clone -q https://github.com/square/PonyDebugger.git /Users/david/Library/PonyDebugger/src/ponydebugger failed with error code 128 in None
Storing complete log in /Users/david/.pip/pip.log
Traceback (most recent call last):
  File "<stdin>", line 2462, in <module>
  File "<stdin>", line 946, in main
  File "<stdin>", line 1794, in after_install
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 511, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Users/david/Library/PonyDebugger/bin/pip', 'install', '-U', '-e', 'git+https://github.com/square/PonyDebugger.git#egg=ponydebugger']' returned non-zero exit status 1

**Comment by srajkovic** [comment]
We're doing some housekeeping and closing old issues. Please reopen if this is still an issue on newer versions. Thanks for opening!
