### ISSUE TITLE
Will the pybonjour issue be fixed ?

### ISSUE THREAD

**Issue by jcampbell05** [square/PonyDebugger#185]
I am unable to run the client due to this issue, when will it be fixed ?

**Comment by justinseanmartin** [comment]
Fixed by #186

**Comment by jcampbell05** [comment]
@justinseanmartin  ran script and still got same issue.

**Comment by justinseanmartin** [comment]
I was able to clone and then install using `python setup.py install`. It isn't as convenient as the command from the readme, will look into getting the script fixed up as well.

**Comment by jcampbell05** [comment]
@justinseanmartin  That worked for me too, thank you.

**Comment by justinseanmartin** [comment]
no problem, sorry for the hassle

**Comment by jcampbell05** [comment]
No problem, thanks for the great tool! :)
