### ISSUE TITLE
Could not find a version that satisfies the requirement pybonjour==1.1.1 

### ISSUE THREAD

**Issue by xiongzenghuidegithub** [square/PonyDebugger#187]
Could not find a version that satisfies the requirement pybonjour==1.1.1 (from ponyd) (from versions: )
No matching distribution found for pybonjour==1.1.1 (from ponyd)

**Comment by justinseanmartin** [comment]
Dupe of #100. You should be unblocked by:

```
git clone git@github.com:square/PonyDebugger.git
cd PonyDebugger
python setup.py install
```

Please confirm this works for you. I've logged #189 to track fixing the install script and/or instructions.

**Comment by xiongzenghuidegithub** [comment]
thanks~~~
