### ISSUE TITLE
Make bootstrap-ponyd.py avilable 

### ISSUE THREAD

**Issue by faisalil** [square/PonyDebugger#207]
Current location: https://cloud.github.com/downloads/square/PonyDebugger/bootstrap-ponyd.py  does not exist, is there plan to have this available somewhere else.

**Comment by foresightyj** [comment]
Same here

**Comment by jaredegan** [comment]
What a disappointing way to not have this work. Does anyone have a copy of this script?

**Comment by bluekurk** [comment]
I just downloaded it from ```  https://github.com/downloads/square/PonyDebugger/bootstrap-ponyd.py ```
and turn to yevgeniy-logachev's [notes] (https://github.com/square/PonyDebugger/issues/198#issuecomment-278992490) if new error occurs.

**Comment by jbarros35** [comment]
-bash: ponyd: command not found
Mac OS Catalina
