### ISSUE TITLE
Build Configuration Name breaks integration

### ISSUE THREAD

**Issue by dschneller** [square/PonyDebugger#30]
I successfully integrated PonyDebugger in my project for the default _Debug_ configuration.
However, we have a few more configurations that pull in different build-settings files (mostly to configure a few pre-processor macros differently for easy switching).

When using one of these configurations (e. g. _Debug (xyz)_) the headers cannot be found anymore. I tried to fix this by setting these values in the PonyDebugger build configurations (analogous to what RestKit does, which BTW works in my setup):

    PRIVATE_HEADERS_FOLDER_PATH = "$(PUBLIC_HEADERS_FOLDER_PATH)/Private";
    PRODUCT_NAME = "$(TARGET_NAME)";
    PUBLIC_HEADERS_FOLDER_PATH = ../../Headers;

This enabled successful compilation. However then the linker complains, and I have not figured out how to resolve that issue:

    ld: library not found for -lSocketRocket
    clang: error: linker command failed with exit code 1 (use -v to see invocation)

_(see full output below)_

It seems to be looking for `libSocketRocket.a` in the wrong place, if I understand this correctly. 

How can I fix this issue? Also: Should I create a pull request for the above change, because it seems to improve the situation a bit already?

**Full error output**
_(wrapped for readability)_

    Ld "/Users/ds/Library/Developer/Xcode/DerivedData/MyProject-gjuonoyeresaysbhbvztuowdvopw/Build/Products/Debug (TEST)-iphonesimulator/MyProject.app/MyProject" normal i386
        cd /Users/ds/MyProject/iOSClient/MyProject
        setenv IPHONEOS_DEPLOYMENT_TARGET 5.0
        setenv PATH "/Volumes/MBP4711HD/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Volumes/MBP4711HD/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin"
 
    /Volumes/MBP4711HD/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
        -arch i386
        -isysroot /Volumes/MBP4711HD/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk
         "-L/Users/ds/Library/Developer/Xcode/DerivedData/MyProject-gjuonoyeresaysbhbvztuowdvopw/Build/Products/Debug (TEST)-iphonesimulator"
        -L/Users/ds/MyProject/iOSClient/MyProject/TestflightSDK 
        "-F/Users/ds/Library/Developer/Xcode/DerivedData/MyProject-gjuonoyeresaysbhbvztuowdvopw/Build/Products/Debug (TEST)-iphonesimulator" 
        -filelist "/Users/ds/Library/Developer/Xcode/DerivedData/MyProject-gjuonoyeresaysbhbvztuowdvopw/Build/Intermediates/MyProject.build/Debug (TEST)-iphonesimulator/MyProject.build/Objects-normal/i386/MyProject.LinkFileList"
        -Xlinker -objc_abi_version -Xlinker 2 -ObjC -all_load -fobjc-arc -fobjc-link-runtime
        -Xlinker -no_implicit_dylibs -mios-simulator-version-min=5.0
        -lSocketRocket
        -licucore
        /Users/ds/Library/Developer/Xcode/DerivedData/MyProject-gjuonoyeresaysbhbvztuowdvopw/Build/Products/Release-iphonesimulator/libPonyDebugger.a
        -framework SystemConfiguration
        /Users/ds/Library/Developer/Xcode/DerivedData/MyProject-gjuonoyeresaysbhbvztuowdvopw/Build/Products/Release-iphonesimulator/libRestKit.a
        -framework CFNetwork
        -lxml2
        -framework MobileCoreServices
        -framework Security
        -framework CoreData
        -framework QuartzCore
        -framework CoreGraphics
        -framework UIKit
        -framework Foundation
        -lTestFlight
        -lz
        -o "/Users/ds/Library/Developer/Xcode/DerivedData/MyProject-gjuonoyeresaysbhbvztuowdvopw/Build/Products/Debug (TEST)-iphonesimulator/MyProject.app/MyProject"

**Comment by srajkovic** [comment]
We're doing some housekeeping and closing old issues. Please reopen if this is still an issue on newer versions. Thanks for opening!
