### ISSUE TITLE
Projects that already use SocketRocket create duplicate symbols

### ISSUE THREAD

**Issue by ljkyser** [square/PonyDebugger#36]
We have a project that already uses SocketRocket for socket io. When I add PonyDebugger to the project and then build I get duplicate symbols errors for the SocketRocket headers since they are already added to our project. Is there a best practice for either 1) isolating the SocketRocket code so that PonyDebugger and our project each maintain their own versions of SocketRocket , or 2) move to one version of SocketRocket and have PonyDebugger and our project both reference the same code? I'd prefer to have one shared version of SocketRocket but I wanted to see if brighter minds than my own have already dealt with this or have any input.

**Comment by allenlinli** [comment]
May I ask how did creating the static lib solve the duplicate symbols problem?
