### ISSUE TITLE
Removed MOCs don't disappear until devtools are reloaded

### ISSUE THREAD

**Issue by erichoracek** [square/PonyDebugger#4]
In an app with multiple child-parent MOCs, the child MOCs that are being registered with the PDDebugger singleton aren't disappearing from the list of MOCs (in devtools) when removeManagedObjectContext: is called. When the _broadcastDatabaseNames method is called (in PDIndexedDBDomainController), the change is seems to be reflected in the broadcasted dbNames array, but it doesn't seem to update in the devtools page until its been reloaded entirely. The removed MOCs show up in the list under "IndexedDB", but don't have anything in any of their tables, so they're obviously disconnected—it's just not updated in the list.  Any ideas?

**Comment by srajkovic** [comment]
We're doing some housekeeping and closing old issues. Please reopen if this is still an issue on newer versions. Thanks for opening!
