### ISSUE TITLE
Integration with Cycript / runtime manipulation

### ISSUE THREAD

**Issue by dtrukr** [square/PonyDebugger#41]
I was thinking about integration of Cycript (http://www.cycript.org) into this project which is a bridge between Objective-C and JavaScript and allow one to manipulate Objective-C runtime in running apps. I have already figured out a way to inject PonyDebugger into running 3rd-party apps (on a jailbroken device), which gives a great way to explore how the layout/UI of different apps is built. But it would certainly be nice to also have a way to access the Objective-C runtime and execute Cycript/Objective-C commands in the Chrome Developer Tools.
What do you guys think? Is there any pointers on how to extend the console in Chrome Developer Tools with additional functionality?

**Comment by srajkovic** [comment]
We're doing some housekeeping and closing old issues. Please reopen if this is still an issue on newer versions. Thanks for opening!
