### ISSUE TITLE
Connection w/ remote server lost when iphone screen off.

### ISSUE THREAD

**Issue by eggie5** [square/PonyDebugger#47]
The connection is lost to the remote server when you turn the screen off on the iphone. Xcode debugger prints this message:
```
Debugger failed with web socket error: The operation couldn’t be completed. Socket is not connected
```
And the device doesn't show up the PonyGateway webpage anymore.

It happens almost instantly after the screen times out.

My app has settings to run the background: Bluetooth Central

**Comment by srajkovic** [comment]
We're doing some housekeeping and closing old issues. Please reopen if this is still an issue on newer versions. Thanks for opening!
