### ISSUE TITLE
Create formula for homebrew

### ISSUE THREAD

**Issue by alias1** [square/PonyDebugger#57]
It would be cool to be able to install this using [homebrew](http://mxcl.github.com/homebrew/)

I'm not too sure how the innards of the bootstrap python script work, but I would think it shouldn't be too hard to create a homebrew formula to work with it?

[Homebrew Formula Cookbook](https://github.com/mxcl/homebrew/wiki/Formula-Cookbook)

**Comment by srajkovic** [comment]
We're doing some housekeeping and closing old issues. While this isn't on our roadmap, we would love a PR. Thanks for opening!
