### ISSUE TITLE
'NSInvalidArgumentException', reason: 'Invalid type in JSON write (NSConcreteMutableAttributedString)'

### ISSUE THREAD

**Issue by benwaa** [square/PonyDebugger#59]
Hi,

I'm getting this error every time I run pony for a second time (or more).
Surprisingly it works fine on the first run.

the error is happening here: https://github.com/square/PonyDebugger/blob/master/ObjC/PonyDebugger/PDDebugger.m#L158

**Comment by davidapgar** [comment]
Going through and closing out old issues. If this is something that still reproduces for you, please reopen it. Thanks!
