### ISSUE TITLE
Add timeout to ponyd

### ISSUE THREAD

**Issue by Tyilo** [square/PonyDebugger#63]
I currently have `ponyd` setup to run at all times on my computer, however `ponyd` doesn't seem to clean up apps/devices, which are no longer runnning.

I currently have 235 apps in `ponyd`, where none of these are running anymore.

Could you add some sort of timeout option to `ponyd`, so apps not updated after 1 hour or 24 hours, are removed from the list?

**Comment by srajkovic** [comment]
We're doing some housekeeping and closing old issues. This is not on our roadmap right now, but we would love a PR if you're interested. Thanks for opening!
