### ISSUE TITLE
No links in the device list

### ISSUE THREAD

**Issue by fdddf** [square/PonyDebugger#93]
Hi, there may be a little bug.
In the device list of google chrome, there is not clickable link to navigate view debug page.
but I can open the link in address bar directly. 
http://192.168.1.41:9000/devtools/devtools.html?host=192.168.1.41:9000&page=1

I'm not sure it's because of chrome version, and it works fine before I upgrade chrome.
PS, the chrome version I'm using is: Version 31.0.1650.57

Thanks.

**Comment by shiki** [comment]
This is happening to me as well. You can see the link when inspecting the page but it's not clickable. It works fine on my other app though.

**Comment by antigp** [comment]
Add CFBundleDisplayName with your application name into Info.plist

**Comment by tpot** [comment]
Thanks @antigp!  Was seeing the same problem but went away after I added a bundle display name.

**Comment by NickEntin** [comment]
Looks like this issue is fixed.  Please reopen if you are still having problems.
